apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wishlist-front
  annotations:
    github.com/project-slug: yaron/wishlist-front
spec:
  type: other
  lifecycle: unknown
  owner: guests
