name: Artifact creator

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 26
        
      - name: Get dependencies
        run: npm install
      
      - name: Compile
        run: npm run build
        
      - name: Tar created files
        run: |
          tar -czf wishlist.tar.gz public

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
             wishlist.tar.gz
